// The starting values behind the portal's curated dropdowns. Each organization edits its own
// copy, so this list is a starting point, not the source of truth.
export const LOOKUP_OPTION_SEED: Record<string, readonly string[]> = {
  position: [
    'Care Coordinator',
    'Case Manager',
    'Registered Nurse',
    'Nurse Practitioner',
    'Physician',
    'Medical Assistant',
    'Billing Specialist',
    'Compliance Analyst',
    'Data Analyst',
    'Software Engineer',
    'Operations Manager',
    'Director',
    'Vice President',
  ],
  employmentType: ['Full-time', 'Part-time', 'Contract', 'Per diem', 'Intern'],
  employmentStatus: ['Probationary', 'Regular', 'Project-based', 'Seasonal', 'Retired'],

  // The client CRM's dropdowns are lookup lists too, so they are seeded here beside the rest.
  clientType: [
    'Hospital',
    'Health system',
    'Skilled nursing facility',
    'Assisted living',
    'Home health agency',
    'Hospice',
    'Physician group',
    'FQHC',
    'Behavioral health provider',
    'Payer',
    'Broker',
    'Vendor',
  ],
  clientServiceLine: [
    'Care management',
    'Utilization review',
    'Population health',
    'Behavioral health',
    'Post-acute network',
    'Revenue cycle',
    'Quality reporting',
    'Credentialing',
    'Staffing',
  ],
  clientSource: [
    'Referral',
    'Conference',
    'Inbound website',
    'Outbound campaign',
    'Existing client expansion',
    'Partner introduction',
    'RFP',
  ],
  clientState: ['NJ', 'NY', 'PA', 'CT', 'DE', 'MD', 'MA', 'VA', 'NC', 'FL', 'OH', 'TX'],
  clientCity: [
    'Trenton',
    'Newark',
    'Jersey City',
    'Princeton',
    'Camden',
    'Philadelphia',
    'New York',
  ],
  clientTag: ['At risk', 'Expansion', 'Executive sponsor', 'Medicare', 'Medicaid', 'Renewal due'],

  // The bluebook's shelves: what kind of document someone is filing.
  bluebookCategory: [
    'Policy',
    'Procedure',
    'Form',
    'Training',
    'Onboarding',
    'Compliance',
    'Org chart',
    'Contact list',
    'Reference',
  ],

  // The rate card's sections; catalog.ts files its seeded services under the first four.
  catalogSection: [
    'Creative services',
    'Social media services',
    'Bundles',
    'Add-ons',
    'Website',
    'IT department',
  ],
}
