import type { EventName } from '@/lib/analytics'

export const bulletinEvents = {
  postCreated: 'bulletin.post.created',
  postCreateFailed: 'bulletin.post.create_failed',
  imageUploaded: 'bulletin.image.uploaded',
  imageUploadFailed: 'bulletin.image.upload_failed',
  postEdited: 'bulletin.post.edited',
  postEditFailed: 'bulletin.post.edit_failed',
  postDeleted: 'bulletin.post.deleted',
  postDeleteFailed: 'bulletin.post.delete_failed',
  postPinned: 'bulletin.post.pinned',
  postPinFailed: 'bulletin.post.pin_failed',
  reactionToggled: 'bulletin.reaction.toggled',
  reactionToggleFailed: 'bulletin.reaction.toggle_failed',
  commentCreated: 'bulletin.comment.created',
  commentCreateFailed: 'bulletin.comment.create_failed',
  commentDeleted: 'bulletin.comment.deleted',
  commentDeleteFailed: 'bulletin.comment.delete_failed',
  acknowledged: 'bulletin.post.acknowledged',
  acknowledgeFailed: 'bulletin.post.acknowledge_failed',
  ackRequested: 'bulletin.post.ack_requested',
  ackRequestFailed: 'bulletin.post.ack_request_failed',
  settingsSaved: 'bulletin.settings.saved',
  settingsSaveFailed: 'bulletin.settings.save_failed',
} as const satisfies Record<string, EventName>
